"""Add category and location parents

Revision ID: 8ba65be7e731
Revises: 6a5bd88084c9
Create Date: 2020-01-15 01:29:51.481457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8ba65be7e731'
down_revision = '6a5bd88084c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_parent_category', 'categories', 'categories', ['parent_id'], ['id'])
    op.add_column('locations', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_parent_location', 'locations', 'locations', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_parent_location', 'locations', type_='foreignkey')
    op.drop_column('locations', 'parent_id')
    op.drop_constraint('fk_parent_category', 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
